### ISSUE TITLE
Build Failed: Cloud Build API has not been used in project

### ISSUE THREAD

**Issue by maengsanha** [CONCAT-internship/smartfarmer-backend#11]
**Describe the bug**
Failure on cloud function deployment

**To Reproduce**
1. Go to '/functions'
2. Type 'gcloud functions deploy'
3. See error

**Expected behavior**
Cloud function should be deployed.

**Screenshots**
```bash
$ gcloud functions deploy my_func --runtime go113 --trigger-http --allow-unauthenticated
> Deploying function (may take a while - up to 2 minutes)...failed.
> ERROR: (gcloud.functions.deploy) OperationError: code=7, message=Build Failed: 
Cloud Build API has not been used in project 327764593197 before or it is disabled. Enable it by visiting
https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=327764593197 then retry. 
If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
```

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Version 10.15.6

**Google cloud sdk**
 - Version: 303.0.0

**Additional context**
After enabled Cloud Build API, it worked.<br>But this error was not shown in last deployment.

**Comment by dides82** [comment]
Same here. I imagine Google Cloud changed their way of deploying their cloud functions. 
From the docs : [cloud-functions-deployment](https://cloud.google.com/functions/docs/deploying#deployment)
--> Container is built via Cloud Build and deployed. This explains need to activate Cloud Build API.

**Comment by maengsanha** [comment]
Enabled Cloud Build API, succeed deploying.
